### PR TITLE
[REF] Refactored download page store integration

### LINKED ISSUE #207: Removal of the multi-column measure doesn't enable the column to be re-assigned in the UI
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected behavior

In multi-column measure view, when a card containing mapped columns is removed the previously mapped columns should become enabled again for mapping.

### Current behavior

Once a card containing mapped columns is removed the mapped columns remain disabled and are not available to me mapped in the UI.

### Error message

_No response_

### Environment

- OS:
- Python/Node version:
- Docker version:
- Docker Compose version:

### How to reproduce

Map a column to a multi-column measure standardized variable, select a term to create a card, map column to the new card/term and then remove the card. When you create another card the mapped column would be disabled when it shouldn't be,

### Anything else?

_No response_

### LINKED ISSUE #333: Refactor download page store integration

### PR DESCRIPTION
**Pull request by rmanaem**
- Closes #333 
- Closes #207 
- Cloees #281 

Changes proposed in this pull request:

- download page new store integration
- regression test for #207 
- regression test for #281 

## Checklist
_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [x] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass
- [ ] If the PR changes the default [Neurobagel `config.json` or any of the term files](https://github.com/neurobagel/communities/tree/main/configs/Neurobagel), make sure their respective counterparts in [neurobagel/communities](https://github.com/neurobagel/communities) have been updated accordingly.

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

File: src/hooks/useAnnotatedVariables.ts [hunk 1]
```diff
@@ -22,12 +22,12 @@ export function useAnnotatedVariables(): AnnotatedVariableGroup[] {
         return acc;
       }
 
-      const existing = acc[standardizedVariableId];
+      const existingGroup = acc[standardizedVariableId];
```
Comment (surchs) [inline src/hooks/useAnnotatedVariables.ts]: 🎉

File: src/hooks/useColumnUniqueValues.ts [hunk 2]
```diff
@@ -2,7 +2,7 @@ import { useMemo } from 'react';
 import { useColumns } from '../stores/FreshNewStore';
 
 /**
- * Returns unique column values for.
+ * Returns the unique values for a column.
```
Comment (surchs) [inline src/hooks/useColumnUniqueValues.ts]: 🎉
