### PR TITLE
[FIX] Keep BIDS data type and descriptions from data dictionary for `Collection` columns

### LINKED ISSUE #328: BIDS Levels/Units for assessment columns in a data dictionary lost on re-upload
### Root cause

We explicitly use the `variable_type` field from the config to set the annotation tool `DataType` which is used to show the appropriate component on value annotation view and we only preserve Levels and units for columns with std vars or `variable_type` defined as categorical or continuous. However, the `collection` type is treated as a special case and we use the continuous component as fallback for it in the value annotation view when the user goes through the column annotation and doesn't explicitly set a data type for it however, we don't have a fallback for it when it is read from the data dictionary. It isn't treated special and there is no fallback for it so it falls through the conditions for categorical and continuous and the data is lost.

### To address

When applying a data dictionary, infer the `dataType` of a collection column based on the presence of levels or units. This preserves categorical data type and levels for Assessment Tool columns coming from uploaded dictionaries while leaving other standardized variables governed by their config type.

- [x] add regression test for this bug
- [x] implement logic to infer the `dataType` of a collection column based on the presence of levels or units
- [x] update unit tests for `applyDataDictionaryToColumns` store util function

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected behavior

If I have a data dictionary where a column has been mapped to "Assessment Tool" and the BIDS Levels descriptions are filled out (i.e., I assigned a "Categorical" data type), if I upload this file I would expect the data type to be detected and the level descriptions loaded from the file.

### Current behavior

Only the mapping of the column to the "Assessment Tool" standardized variable is loaded - the level descriptions and data type are not detected.

This also means that on the value annotation page, the column looks like it is continuous again (which seems to be the default data type for assessment columns, see also https://github.com/neurobagel/annotation-tool/issues/380), prompting the user to add a units description even though they previously provided individual level descriptions.

### Environment

- OS:
- Python/Node version:
- Docker version:
- Docker Compose version:

### How to reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rmanaem**
- Closes #328 

Changes proposed in this pull request:

- Added regression test for the bug
- Implement logic to infer collection column data type based on the presence of levels/units
- Add new unit test cases for the inference logic

## Checklist
_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [x] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass
- [ ] If the PR changes the default [Neurobagel `config.json` or any of the term files](https://github.com/neurobagel/communities/tree/main/configs/Neurobagel), make sure their respective counterparts in [neurobagel/communities](https://github.com/neurobagel/communities) have been updated accordingly.

For new features:
- [ ] Tests have been added

For bug fixes:
- [x] There is at least one test that would fail under the original bug conditions.

## Summary by Sourcery

Improve handling of data dictionary metadata for collection variables when applying it to columns.

Bug Fixes:
- Fix incorrect or missing data type assignment for collection variables by inferring categorical vs continuous types from levels or units in the data dictionary.

Enhancements:
- Populate level metadata and standardized term mappings for categorical collection variables based on data dictionary levels and annotations.
- Populate units and optional standardized format for continuous collection variables using data dictionary metadata.

Tests:
- Add unit tests covering data type inference and metadata population for collection variables with levels or units.
- Add an end-to-end regression test ensuring collection variables are correctly interpreted from the data dictionary in the UI.

### CODE REVIEW

**Review by surchs — CHANGES_REQUESTED** [review]
Thanks @rmanaem for taking this on.

The current implementation does not account for the levels in the data dictionary being wrong (i.e. similar to #374) - and would prevent adding descriptions for levels in the actual data. Left some comments below, but please also add a test to ensure that descriptions can be added / make it to the downloaded data dictionary also for collections.

File: src/utils/data-utils.ts [hunk 1]
```diff
@@ -217,6 +217,49 @@ interface ColumnDataShape {
...
 }
 
+interface LevelMap {
+  [key: string]: { description: string; standardizedTerm: string };
+}
+
+function buildCategoricalLevels(
+  allValues: string[] | undefined,
+  missingValues: string[] | undefined,
+  dictLevels: { [key: string]: { Description: string; TermURL?: string } } | undefined,
```
Comment (surchs) [inline src/utils/data-utils.ts]: Why do you need to expand these parameters? They are all part of the `column` object, no? I'd say that's a good thing and keeps the function signature focused on the important parts.

File: src/utils/data-utils.ts [hunk 2]
```diff
@@ -217,6 +217,49 @@ interface ColumnDataShape {
...
+    .reduce(
+      (acc, value) => ({
+        ...acc,
+        [value]: { description: '', standardizedTerm: '' },
+      }),
+      {} as LevelMap
+    );
+
+  const resolvedDictLevels = dictLevels ?? {};
+  const resolvedAnnotationLevels = annotationLevels ?? {};
```
Comment (surchs) [inline src/utils/data-utils.ts]: I still find this a bit confusing. I.e. what is the benefit over just doing `dictLevels?.[value]` below? You're doing `dictLevels -> resolvedDictLevels (what is that?) -> dictLevel`. I think the reason you're doing this is to guard against `dictLevels` being `undefined` - but this implementation creates a bit of clutter

**Review by surchs — CHANGES_REQUESTED** [review]
Thanks @rmanaem for factoring this out - but this new function should now also have some unit tests to assert the core functions. I.e.

- [x] allValues become levels
- [x] allValues become levels but not missingValues
- [x] existing descriptions are matched with new levels
- [x] descriptions from terms not in allValues don't cause levels to be created (i.e. old bug)
- [x] standardizedTerm annotations are matched with new levels
- [x] unrecognized standardized terms do not show up in the output levelsmap

and maybe something else I'm missing. Some of these may be covered from the calling functions - but the new function needs its own unit tests

File: src/utils/data-utils.ts (hunk 1 above)
Comment (rmanaem) [reply src/utils/data-utils.ts]: Will pass a group object of column, columnData, and standardizedTerms, `{ column, columnData, standardizedTerms }` and we can destructure internally.

**Review by surchs — APPROVED** [review]
Thanks @rmanaem, works great, looks clean.

🧑‍🍳
