### PR TITLE
[ENH] Redesign the column annotation card to reduce the existing whitespace and improve ux

### LINKED ISSUE #253: Description field "save status" element shifts UI elements around
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected behavior

All UI elements are in the same place whether my description field is in "neutral", "Saving...", or "Saved" state.

### Current behavior

The debounce notification area unmounts in "neutral" state, thus shifting elements below it:
https://github.com/user-attachments/assets/59ba1236-1e6f-4769-9acb-fce8df601f58

### Error message

_No response_

### Environment

- OS:
- Python/Node version:
- Docker version:
- Docker Compose version:

### How to reproduce

type in description box

### Anything else?

We should fix the whitespace reserved by the debounce status field - whether it is empty or shows something

### LINKED ISSUE #310: (whitespace) the Description field uses too much vertical space
Problem:
The description field by default takes up too much vertical white space, thus forcing all parent elements to stretch as well. This ends up wasting screen real estate.

Image

Desired:
The description component is by default only [`1em` high](https://developer.mozilla.org/en-US/docs/Web/CSS/length#em).

### LINKED ISSUE #311: (whitespace) remove empty area below column cards
Problem:

there is some kind of white box at the bottom of the column annotation step
Image

Desired behaviour:
The visible area for "column cards" (the visual elements representing each column in the column annotation step) should extend all the way to the bottom of the screen - possibly with the exception for the space reserved for the "previous" and "next" buttons (but see #234)

### LINKED ISSUE #407: Modify the column annotation card to reduce the existing whitespace and improve ux
in #312 we designed the new UI for the column annotation card and the layout of how the cards should be displayed in the column annotation view. see https://github.com/neurobagel/annotation-tool/issues/312#issuecomment-3843598583 as the final version of the design. This issue will take on the implementation of the new design.

Since addressing this issue would require changing and refactoring the `EditDescription` component and the layout of the `ColumnAnnotationCard`, check if hte following issues have been addressed with the changes:
- https://github.com/neurobagel/annotation-tool/issues/310
- https://github.com/neurobagel/annotation-tool/issues/253
- https://github.com/neurobagel/annotation-tool/issues/311

### PR DESCRIPTION
**Pull request by rmanaem**
- Closes #407 
- Closes #253 
- Closes #311 
- Closes #310 

Changes proposed in this pull request:

-  refactor DescriptionEditor to compact expandable design
    - Implement expandable text area with focus states
    - Add save status indicator (dot) with tooltip
    - Update component tests to verify new UI interactions

- refactor ColumnAnnotationCard to compact layout
    - Align data type and variable mapping controls
    - Remove redundant labels for a cleaner interface
    - Update component tests for new layout assertions

- integrate compact components into ColumnAnnotation
    - Update list rendering to use new compact cards

- update tests for UI changes
    - Update assertions for shortened data type labels (Cont/Cat)
    - Verify scroll interactions with new layout

## Checklist
_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [x] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass
- [ ] If the PR changes the default [Neurobagel `config.json` or any of the term files](https://github.com/neurobagel/communities/tree/main/configs/Neurobagel), make sure their respective counterparts in [neurobagel/communities](https://github.com/neurobagel/communities) have been updated accordingly.

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

## Summary by Sourcery

Redesign the column annotation UI to make better use of space and improve usability while keeping existing behavior intact.

Enhancements:
- Restyle the column annotation card with a compact, grid-based layout that separates description, data type, and mapped variable in a single row under a simplified header.
- Introduce a sticky global header row for the column annotation list to label the description, data type, and mapped variable columns and keep them visible while scrolling.
- Update the description editor to be more compact by default, expanding on focus with visual save-status indicators and an updated placeholder experience.
- Adjust the column annotation container to use an internal scrollable region for cards, improving navigation in tall datasets.

Tests:
- Update component and end-to-end tests to align with the new UI labels, compact data type button text, scrolling container, and description save indicators.

### CODE REVIEW

File: src/components/ColumnAnnotation.tsx [hunk 1]
```diff
@@ -64,32 +65,57 @@ function ColumnAnnotation() {
...
+        <div className="p-4 flex-shrink-0">
+          <Instruction title="Column Annotation" className="mb-0">
+            <ColumnAnnotationInstructions />
+          </Instruction>
+        </div>
+
+        {/* Global Header Row - Sticky */}
+        <Box
+          className="sticky top-0 z-10 mx-4 mt-2 border border-blue-200 border-b-0 shadow-sm rounded-t-lg backdrop-blur-sm bg-opacity-95 bg-gray-50"
+          sx={{ borderColor: 'grey.200' }}
```
Comment (surchs) [inline src/components/ColumnAnnotation.tsx]: why do you need to mix `sx` and `className` here?

File: src/components/ColumnAnnotation.tsx [hunk 2]
```diff
@@ -64,32 +65,57 @@ function ColumnAnnotation() {
...
+        >
+          {/* Row 1: Main Labels */}
+          <div className="grid grid-cols-[1fr_140px_250px] gap-4 px-4 pt-3 pb-1 items-end border-b border-gray-200">
```
Comment (surchs) [inline src/components/ColumnAnnotation.tsx]: why are we hard-coding the pixel widths here? I would expect that

- widths are some ratio of viewport width
- there is a minimum viewport width under which we start complaining that the screen is not optimized (and we could start allowing linebreaks and other ugly stuff)
-
